### ISSUE TITLE
Folder naming convention

### ISSUE THREAD

**Issue by patzomir** [webdata/SEMANTiCS2017-posters#1]
@Vehnem , I'm writing on behalf for the euBusinessGraph: Company and Economic Data for Innovative Products and Services. Could you please confirm how should I name the folder in "papers_todo/"? Is  industry_163_Alexiev ok? Also should I create a pull request once we're ready?
Thanks,
Plamen

**Comment by webdata** [comment]
Dear Plamen, 
Thanks for your message. industry_163_Alexiev  is perfectly OK!

Best,
Javier
